# Generated by Django 5.0.3 on 2024-03-15 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_name', models.CharField(max_length=20)),
                ('author_name', models.CharField(max_length=20)),
                ('rate', models.IntegerField()),
            ],
        ),
    ]
